### ISSUE TITLE
Crash deleting intermediate connected blocks

### ISSUE THREAD

**Issue by AndreaGimelli** [NeVerTools/NeVer2#4]
Trying deleting intermediating blocks, the programs crashes.
Example: in a network made up with multiple blocks
 as the one uploaded below, when i delete a block the program crashes.
<img width="1552" alt="Schermata 2021-08-23 alle 12 04 27" src="https://user-images.githubusercontent.com/81355251/130429572-c5850734-44a2-4540-9124-8311d2e76a16.png">

Terminal error:
(test) andrea@MBP-di-Andrea NeVer2 % python never2.py
qt.qpa.fonts: Populating font family aliases took 906 ms. Replace uses of missing font family "Calibri" with one that exists to avoid this cost. 
Traceback (most recent call last):
  File "/Users/andrea/Desktop/NeVer2/never2/view/drawing/renderer.py", line 449, in delete_node
    self.update_network_from(next_node_id, k)
  File "/Users/andrea/Desktop/NeVer2/never2/view/drawing/renderer.py", line 497, in update_network_from
    NodeOps.update_node_input(node, in_dim)
  File "/Users/andrea/Desktop/NeVer2/never2/core/controller/nodewrapper.py", line 134, in update_node_input
    node.update_input(in_dim)
  File "/Users/andrea/opt/anaconda3/envs/test/lib/python3.9/site-packages/pynever/nodes.py", line 149, in update_input
    self.__init__(self.identifier, in_dim, self.out_features, self.weight, self.bias, self.has_bias)
  File "/Users/andrea/opt/anaconda3/envs/test/lib/python3.9/site-packages/pynever/nodes.py", line 132, in __init__
    raise Exception(weight_error)
Exception: Weight dimensions should be equal to out_features (100) and in_features (11520) respectively.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/andrea/Desktop/NeVer2/never2/view/drawing/scene.py", line 471, in <lambda>
    .connect(lambda: self.delete_selected())
  File "/Users/andrea/Desktop/NeVer2/never2/view/drawing/scene.py", line 676, in delete_selected
    new_tuple = self.renderer.delete_node(self.scene.blocks[item].block_id)
  File "/Users/andrea/Desktop/NeVer2/never2/view/drawing/renderer.py", line 456, in delete_node
    raise Exception(e)
Exception: Weight dimensions should be equal to out_features (100) and in_features (11520) respectively.
zsh: abort      python never2.py
(test) andrea@MBP-di-Andrea NeVer2 % python never2.py
qt.qpa.fonts: Populating font family aliases took 867 ms. Replace uses of missing font family "Calibri" with one that exists to avoid this cost. 
Traceback (most recent call last):
  File "/Users/andrea/Desktop/NeVer2/never2/view/drawing/renderer.py", line 449, in delete_node
    self.update_network_from(next_node_id, k)
  File "/Users/andrea/Desktop/NeVer2/never2/view/drawing/renderer.py", line 497, in update_network_from
    NodeOps.update_node_input(node, in_dim)
  File "/Users/andrea/Desktop/NeVer2/never2/core/controller/nodewrapper.py", line 134, in update_node_input
    node.update_input(in_dim)
  File "/Users/andrea/opt/anaconda3/envs/test/lib/python3.9/site-packages/pynever/nodes.py", line 149, in update_input
    self.__init__(self.identifier, in_dim, self.out_features, self.weight, self.bias, self.has_bias)
  File "/Users/andrea/opt/anaconda3/envs/test/lib/python3.9/site-packages/pynever/nodes.py", line 132, in __init__
    raise Exception(weight_error)
Exception: Weight dimensions should be equal to out_features (10) and in_features (2880) respectively.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/andrea/Desktop/NeVer2/never2/view/drawing/scene.py", line 471, in <lambda>
    .connect(lambda: self.delete_selected())
  File "/Users/andrea/Desktop/NeVer2/never2/view/drawing/scene.py", line 676, in delete_selected
    new_tuple = self.renderer.delete_node(self.scene.blocks[item].block_id)
  File "/Users/andrea/Desktop/NeVer2/never2/view/drawing/renderer.py", line 456, in delete_node
    raise Exception(e)
Exception: Weight dimensions should be equal to out_features (10) and in_features (2880) respectively.
zsh: abort      python never2.py

**Comment by sdemarch** [comment]
Delete block -> Try reconnecting, otherwise split.

(chain update not working?)

**Comment by AndreaGimelli** [comment]
No, deleting a block between two other blocks generates an unexpected exit of the program

https://user-images.githubusercontent.com/81355251/130454892-31adc5f8-191d-4c80-95ee-9311d16a46d2.mov
